logging.level:
  org.springframework.security: TRACE
server:
  port : 8081
spring:
  security:
    saml2:
      relyingparty:
        registration:
          authproxy:
            signing.credentials:
              - private-key-location: classpath:credentials/authproxy-server-key-8.pem
                certificate-location: classpath:credentials/authproxy-server.pem
            assertingparty:
              metadata-uri: http://localhost:8080/realms/paychex/protocol/saml/descriptor
              verification.credentials:
                - certificate-location: "classpath:credentials/authproxy-server.pem"